config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
  	collection { post :import }
    resources :contacts
  end
  root to: 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :contacts

  validates_presence_of :title

  def to_csv(options = {})
    CSV.generate(options) do |csv|
      values = ["id", "First Name" ,"Last Email","Description","Email Addresses", "Phone Numbers"]
      csv << values
      self.contacts.each do |contact|
      	id = contact.id
        first_name = contact.first_name
        last_name = contact.last_name 
        description = contact.description 
        email_addresses = contact.email_addresses.to_s.gsub(/["\[\]]/, "") 
        phone_numbers = contact.phone_numbers.to_s.gsub(/["\[\]]/, "")
        data = [id, first_name, last_name, description, email_addresses, phone_numbers]
        csv << data
      end
      csv
    end
  end


  def import(file)
    CSV.foreach(file.path, headers:true) do row
      contact = Book.contacts.find_by_id(row["id"]) || new
      Contact.create! row.to_hash
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :book
  
  serialize :phone_numbers, Array
  serialize :email_addresses, Array

  validates_presence_of :first_name, :last_name
  validate :all_email_addresses_are_valid
  validate :all_phone_numbers_are_valid
  validate :uniqueness_of_full_name
  validate :presence_of_phone_or_email
  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  PHONE_REGEX = /\A([0-9\\x(\)\/\+ \-]*)\Z/i

  private
    def all_email_addresses_are_valid
      unless self.email_addresses.nil?
        self.email_addresses.each do |email_address|
          puts email_address
          if !email_address.strip.match(EMAIL_REGEX)
            errors.add(:email_address, " '#{email_address}' is not in a valid format. ")
          end
        end
      end
    end

    def all_phone_numbers_are_valid
      unless self.phone_numbers.nil?
        self.phone_numbers.each do |phone_number|
          puts phone_number
          if !phone_number.strip.match(PHONE_REGEX)
            errors.add(:phone_number, " '#{phone_number}' is not in a valid format. ")
          end
        end
      end
    end

    def uniqueness_of_full_name
      if self.book.contacts.where(first_name: self.first_name.strip, last_name: self.last_name.strip).count > 0 
        errors.add(:full_name, " '#{first_name} #{last_name}' already exists. ")
      end
    end

    def presence_of_phone_or_email
    	if self.phone_numbers.count == 0 && self.email_addresses.count == 0
    	  errors.add(:phone_or_email, " Please Enter atleast 1 phone number or email address. ")
    	end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :set_locale

  protect_from_forgery with: :exception

  private
    def set_locale
    	I18n.locale = params[:locale] if params[:locale]
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy, :import]

  def index
    @all_books = current_user.books
  end

  def new
    @book = Book.new
  end

  def create
    puts params.inspect
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to @book
    else
      redirect_to root_path
    end
  end

  def show
    @contacts = @book.contacts
    respond_to do |format|
      format.html
      format.csv { send_data @book.to_csv }
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Updated book'
    else
      render action: 'edit'
    end
  end
  
  def import
    Book.import(params[:file])
    redirect_to redirect_to @book, notice: "People imported."
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end
  
    def book_params
      params.require(:book).permit(:title, :description, :user_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:new, :create, :show, :edit, :update, :destroy]


  def index
    redirect_to @book
  end

  def new
    @contact = @book.contacts.build
  end

  def create
    updated_params = contact_params
    updated_params['phone_numbers']=updated_params['phone_numbers'].split(',')
    updated_params['email_addresses']=updated_params['email_addresses'].split(',')
    @contact = Contact.new(updated_params)
    @contact.book = @book
    if @contact.save
      redirect_to @book
    else
      render action: 'new'
    end
  end

  def show
    
  end

  def edit
  end

  def update
    updated_params = contact_params
    updated_params['phone_numbers']=updated_params['phone_numbers'].split(',')
    updated_params['email_addresses']=updated_params['email_addresses'].split(',')

    if @contact.update(updated_params)
      redirect_to @contact.book, notice: 'Updated contact'
    else
      render action: 'edit'
    end
  end
  def destroy
    @contact.destroy
    redirect_to @book
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end
  
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :description, :phone_numbers, :email_addresses, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/books/_form.html.slim
= form_for @book do |f|
  - if @book.errors.count > 0
    div.errors
      - @book.errors.full_messages.each do |error|
        | #{error}
  span#err_span
    | Please fill out all required.

  .field
    = f.label :title
    | (required)
    asd
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save', id: "validate_submit"
    span[style="opacity:0;"]
      = f.submit 'Save', id: "submit_book"

= link_to 'Back', books_path

app/views/books/edit.html.slim
h1 
  | Edit @book

= render 'form' 

app/views/books/index.html.slim
h2
  center 
    = t("books.my_address_books")

center 
  - @all_books.each_with_index do |address_book, count|
    p
      | #{count+1}) #{address_book.title} - 
      = link_to "View", address_book
      | #{" | "}
      = link_to "Edit", edit_book_path(address_book), :method => :get
center
  h4
    = link_to "Create New Address Book", new_book_path, :method => :get

app/views/books/show.html.slim
p
  strong
    | name:
  = @book.title
p
  strong
    | description:
  = @book.description

table#contacts.display[cellspacing="0" width="100%"]
  thead
    tr
      th
        | Name
      th
        | Email Addresses
      th
        | Phone Numbers
      th
        | View
      th
        | Edit
      th
        | Delete
  tbody
    - @contacts.each do |contact|
      tr
        td
          = contact.first_name + " " + contact.last_name
        td
          = contact.email_addresses.to_s.gsub(/["\[\]]/, "") if contact.email_addresses
        td
          = contact.phone_numbers.to_s.gsub(/["\[\]]/, "") if contact.phone_numbers
        td
          = link_to 'View', book_contact_path(@book, contact)
        td
          = link_to 'Edit', edit_book_contact_path(@book, contact), :method => :get
        td 
          = link_to 'Delete', book_contact_path(@book, contact), :method => :delete, data: { confirm: 'Are you sure you want to delete this contact?' }

script
  | $(document).ready(function() { $('#contacts').DataTable( { "columnDefs": [ { "orderable": false, "targets": [ 3,4,5 ] } ] } ); } ); 


p  
  = link_to "Create Contact", new_book_contact_path(@book), :method => :get
p
  = link_to "Download Contacts (CSV File)", book_path(format:"csv")

p 
  | TODO: Import Contacts with CSV File (Available fields: id, first_name, last_name, description(optional), email_addresses, phone_numbers)
  = form_tag import_books_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Import"
p  
  = link_to "Back to Address books", root_path, :method => :get

app/views/contacts/_form.html.slim
= form_for([@contact.book, @contact]) do |f|
  - if @contact.errors.count > 0
    div.errors
      - @contact.errors.full_messages.each do |error|
        | #{error}
  span#err_span
    | Please fill out all required.

  .field
    = f.label :first_name
    |(required)
    = f.text_field :first_name
  .field
    = f.label :last_name
    |(required)
    = f.text_field :last_name
  .field
    = f.label :description
    = f.text_field :description
  br
  span 
    | An Email Address or Phone Number is required
  .field
    = f.label :phone_numbers 
    |(seperated by commas)
    = f.text_field :phone_numbers, :value => @contact.phone_numbers.map { |i|  i.to_s }.join(",")
  .field
    = f.label :email_addresses
    |(seperated by commas)
    = f.text_field :email_addresses, :value => @contact.email_addresses.map { |i|  i.to_s }.join(",")
  .actions
    = f.submit 'Save', id: "validate_submit_2"
    span[style="opacity:0;"]
      = f.submit 'Save', id: "submit_book"

= link_to 'Back', @contact.book

app/views/contacts/edit.html.slim
h1 
  | Edit Contact

= render 'form' 

app/views/contacts/index.html.slim
h2
  center My Address Books

center 
  - @all_books.each_with_index do |address_book, count|
    p
      | #{count+1} #{address_book.title} - 
        = link_to "View ", address_book
        | | 
        = link_to "Edit ", edit_book_path(address_book), :method => :get

center
  h4
    = link_to "Create New Address Book", new_book_path

app/views/contacts/new.html.slim
= render 'form'

app/views/contacts/show.html.slim
p
  = "Name: " + @contact.first_name + " " + @contact.last_name
p
  = "Email(s): " + @contact.email_addresses.to_s.gsub(/["\[\]]/, "") if @contact.email_addresses
p
  = "Phone Number(s):" + @contact.phone_numbers.to_s.gsub(/["\[\]]/, "") if @contact.phone_numbers

p
  | TODO: Set-up mailer for users to share contact details via email with others
p
  = link_to 'Back', @contact.book

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.10/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.10/js/jquery.dataTables.js"></script>
</head>
<body style="background-color: #f1f1f1">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if current_user %>
    <p><%= link_to current_user.email, edit_user_registration_path %></a></p>
    <p><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "navbar-brand" %></p>
  <% end %>
  <p><%= link_to_unless_current "English", locale: "en" %>| <%= link_to_unless_current "Russian", locale: "ru" %> (only root page index header for now) </p>
  <%= yield %>

</body>
</html>